import { ConfigService } from '@nestjs/config';
import { spawn } from 'node:child_process';
import { describe, expect, it } from 'vitest';
import { VideoFrameExtractor } from '../src/modules/submissions/infrastructure/video-frame-extractor.js';
import { grayscale9x8 } from './support/proof-fixtures.js';
import { differenceHash, hammingDistance } from '../src/modules/submissions/domain/proof-forensics.js';

/// Config stub with the production defaults.
function extractor(overrides: Record<string, unknown> = {}): VideoFrameExtractor {
  const values: Record<string, unknown> = {
    AI_VERIFICATION_VIDEO_FRAMES: 3,
    AI_VERIFICATION_FFMPEG_TIMEOUT_MS: 30_000,
    ...overrides,
  };
  return new VideoFrameExtractor({
    get: (key: string) => values[key],
  } as unknown as ConfigService<never, true>);
}

/// A real encoded video, generated by ffmpeg rather than committed.
///
/// `testsrc` is a moving pattern, so frames sampled at different timestamps
/// genuinely differ — which is what makes the "samples across the clip"
/// assertion below mean something. A static colour source would pass it
/// while proving nothing.
function makeVideo(seconds = 3): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const child = spawn('ffmpeg', [
      '-f', 'lavfi',
      '-i', `testsrc=duration=${seconds}:size=320x240:rate=10`,
      '-pix_fmt', 'yuv420p',
      '-f', 'mp4',
      '-movflags', 'frag_keyframe+empty_moov',
      'pipe:1',
    ], { stdio: ['ignore', 'pipe', 'ignore'] });
    const chunks: Buffer[] = [];
    child.stdout.on('data', (chunk: Buffer) => chunks.push(chunk));
    child.on('error', reject);
    child.on('close', (code) =>
      code === 0 ? resolve(Buffer.concat(chunks)) : reject(new Error(`ffmpeg exited ${code}`)));
  });
}

/// Resolved at module scope, not in `beforeAll`.
///
/// `it.runIf` is evaluated while tests are being collected, which happens
/// before any hook runs — so a flag set in `beforeAll` is still false when
/// the guard reads it and every case silently skips. That is a trap worth
/// naming: a suite that skips itself looks exactly like a suite that passes.
const available = await extractor().isAvailable();

describe('VideoFrameExtractor', () => {
  it('reports whether ffmpeg is usable', () => {
    expect(typeof available).toBe('boolean');
  });

  it.runIf(available)('extracts the requested number of frames as real JPEGs', async () => {
    const frames = await extractor().extract(await makeVideo());
    expect(frames).toHaveLength(3);
    for (const frame of frames) {
      // JPEG SOI marker: proof these are decodable images and not, say,
      // ffmpeg's error text captured into a buffer.
      expect(frame[0]).toBe(0xff);
      expect(frame[1]).toBe(0xd8);
      expect(frame.length).toBeGreaterThan(500);
    }
  });

  // The reason frames are sampled across the clip rather than taken from the
  // start: an opening frame is often a blur or a floor, and judging proof on
  // it would reject honest players for a bad quarter-second.
  it.runIf(available)('samples different moments rather than the same frame', async () => {
    const frames = await extractor().extract(await makeVideo());
    const hashes = await Promise.all(
      frames.map(async (frame) => differenceHash(await grayscale9x8(frame))),
    );
    // A null hash means a flat frame that cannot be fingerprinted; the
    // synthetic clip is a moving gradient, so both ends must hash.
    const first = hashes[0];
    const last = hashes[hashes.length - 1];
    expect(first).not.toBeNull();
    expect(last).not.toBeNull();
    expect(hammingDistance(first!, last!)).toBeGreaterThan(0);
  });

  it.runIf(available)('honours the frame count', async () => {
    const frames = await extractor({ AI_VERIFICATION_VIDEO_FRAMES: 1 }).extract(await makeVideo());
    expect(frames).toHaveLength(1);
  });

  // A clip too short to sample across still has to yield something, or short
  // video proof would always escalate.
  it.runIf(available)('still yields a frame from a sub-second clip', async () => {
    const frames = await extractor().extract(await makeVideo(0.5));
    expect(frames.length).toBeGreaterThanOrEqual(1);
  });

  // Garbage in must not throw: this runs inside a queue worker, where an
  // exception would fail the whole job and retry every side effect with it.
  it.runIf(available)('returns nothing for bytes that are not a video', async () => {
    const frames = await extractor().extract(Buffer.from('this is not a video'));
    expect(frames).toEqual([]);
  });

  it.runIf(available)('returns nothing for an empty buffer', async () => {
    expect(await extractor().extract(Buffer.alloc(0))).toEqual([]);
  });
});
