import { Injectable } from '@nestjs/common';
import { DatabaseService } from '../../../infrastructure/database/database.service.js';

export interface GeofencingSubscriptionRecord {
  readonly id: string;
  readonly userQuestId: string;
  readonly placeId: string;
  readonly providerSubscriptionId: string | null;
  readonly providerSubscriptionIds: readonly string[];
  readonly status: 'pending' | 'active' | 'failed' | 'expired';
  readonly callbackSecret: string;
  readonly startsAt: Date;
  readonly expiresAt: Date;
  /**
   * NOKIA — registered with Network-as-Code; events arrive from the network.
   * DEMO_HARNESS — created by the hackathon harness and known only here, so
   * an event on it was generated by us and must never be presented as a
   * carrier observation.
   */
  readonly origin: GeofenceOrigin;
}

export type GeofenceOrigin = 'NOKIA' | 'DEMO_HARNESS';

export interface GeofencingEventRecord {
  readonly type: 'ENTER' | 'EXIT';
  readonly occurredAt: Date;
  /** Carried on the event itself, so a deleted subscription cannot erase it. */
  readonly origin: GeofenceOrigin;
}

interface SubscriptionRow {
  id: string;
  user_quest_id: string;
  place_id: string;
  provider_subscription_id: string | null;
  provider_subscription_ids: string[];
  status: 'pending' | 'active' | 'failed' | 'expired';
  callback_secret: string;
  starts_at: Date;
  expires_at: Date;
  origin: GeofenceOrigin;
}

/**
 * Persistence for CAMARA Geofencing Subscriptions and the entry/exit
 * events they deliver. Events are only ever read back within the
 * subscription's own window, which is the quest's window — presence
 * outside the quest is not evidence of completing it.
 */
@Injectable()
export class GeofencingRepository {
  constructor(private readonly database: DatabaseService) {}

  /// Claims the single subscription slot for an assignment. Returns null
  /// when one already exists, so a retried quest.assigned event cannot
  /// create a second provider subscription.
  async create(input: {
    userQuestId: string;
    placeId: string;
    callbackSecret: string;
    startsAt: Date;
    expiresAt: Date;
    /** Defaults to NOKIA: the adapter is the only ordinary caller. */
    origin?: GeofenceOrigin;
  }): Promise<GeofencingSubscriptionRecord | null> {
    const result = await this.database.query<SubscriptionRow>(
      `INSERT INTO geofencing_subscriptions (user_quest_id, place_id, callback_secret, starts_at, expires_at, origin)
       VALUES ($1, $2, $3, $4, $5, $6)
       ON CONFLICT (user_quest_id) DO NOTHING
       RETURNING *`,
      [input.userQuestId, input.placeId, input.callbackSecret, input.startsAt, input.expiresAt, input.origin ?? 'NOKIA'],
    );
    return result.rows[0] ? this.map(result.rows[0]) : null;
  }

  /**
   * Hands a subscription to the demo harness.
   *
   * Called when the harness is about to deliver events to a subscription it
   * did not create — typically one Nokia registration FAILED for (nothing can
   * call back to a laptop), which otherwise leaves the mandatory geofence
   * signal permanently unavailable.
   *
   * Two things change together, and both are honest. The status becomes
   * active, because events are about to arrive and they should be read. The
   * origin becomes DEMO_HARNESS, because from this moment the events on it
   * are ours — leaving it NOKIA would stamp a generated event as
   * carrier-delivered, which is the one thing the provenance exists to
   * prevent.
   *
   * It errs conservatively: a genuine Nokia event landing here afterwards
   * would also be marked DEMO_HARNESS. Understating what the network told us
   * is the safe direction to be wrong in.
   */
  async adoptForHarness(id: string): Promise<void> {
    await this.database.query(
      `UPDATE geofencing_subscriptions
          SET status = 'active', origin = 'DEMO_HARNESS', failure_reason = NULL
        WHERE id = $1`,
      [id],
    );
  }

  async markActive(id: string, providerSubscriptionIds: readonly string[]): Promise<void> {
    await this.database.query(
      `UPDATE geofencing_subscriptions
       SET status = 'active', provider_subscription_id = $2, provider_subscription_ids = $3::text[]
       WHERE id = $1`,
      [id, providerSubscriptionIds[0] ?? null, providerSubscriptionIds],
    );
  }

  async markFailed(id: string, reason: string): Promise<void> {
    await this.database.query(
      `UPDATE geofencing_subscriptions SET status = 'failed', failure_reason = $2 WHERE id = $1`,
      [id, reason.slice(0, 500)],
    );
  }

  async findById(id: string): Promise<GeofencingSubscriptionRecord | null> {
    const result = await this.database.query<SubscriptionRow>(
      'SELECT * FROM geofencing_subscriptions WHERE id = $1',
      [id],
    );
    return result.rows[0] ? this.map(result.rows[0]) : null;
  }

  async findByUserQuest(userQuestId: string): Promise<GeofencingSubscriptionRecord | null> {
    const result = await this.database.query<SubscriptionRow>(
      'SELECT * FROM geofencing_subscriptions WHERE user_quest_id = $1',
      [userQuestId],
    );
    return result.rows[0] ? this.map(result.rows[0]) : null;
  }

  /// Idempotent on the provider's own event id where one is supplied, so a
  /// redelivered notification is not counted twice.
  /**
   * Clears events this deployment's demo harness generated for one quest.
   *
   * Only `DEMO_HARNESS` rows, and that restriction is the whole point: a
   * Nokia-delivered event is a fact about the network and is never touched.
   *
   * Needed because geofence events PERSIST and a demo switches scenarios.
   * Deliver an entry for the supportive case, then pick the contradicting
   * case, and the agent is handed "the network says the device was never
   * here" alongside "an entry was recorded" — an incoherent pair it can only
   * escalate. Which it did, correctly, and the demo looked broken as a
   * result. Clearing our own fabrications between scenarios is what makes
   * each one a clean question.
   */
  async clearHarnessEvents(userQuestId: string): Promise<number> {
    const result = await this.database.query(
      `DELETE FROM geofencing_events event
        USING geofencing_subscriptions subscription
        WHERE subscription.id = event.subscription_id
          AND subscription.user_quest_id = $1
          AND event.origin = 'DEMO_HARNESS'`,
      [userQuestId],
    );
    return result.rowCount ?? 0;
  }

  async recordEvent(input: {
    subscriptionId: string;
    type: 'ENTER' | 'EXIT';
    occurredAt: Date;
    providerEventId?: string;
  }): Promise<void> {
    // Provenance is inherited from the subscription rather than taken from
    // the caller. The callback endpoint has no way to assert where an event
    // came from — and must not have one, or the harness would be a back door
    // that can label itself Nokia-delivered.
    await this.database.query(
      `INSERT INTO geofencing_events (subscription_id, event_type, occurred_at, provider_event_id, origin)
       SELECT $1, $2, $3, $4, subscription.origin
       FROM geofencing_subscriptions subscription WHERE subscription.id = $1
       ON CONFLICT (subscription_id, provider_event_id) WHERE provider_event_id IS NOT NULL DO NOTHING`,
      [input.subscriptionId, input.type, input.occurredAt, input.providerEventId ?? null],
    );
  }

  /// Events inside the quest's own window only. `windowEnd` is the
  /// submission time, so entering the area after submitting proof is not
  /// treated as evidence for that proof.
  async eventsInWindow(
    userQuestId: string,
    windowStart: Date,
    windowEnd: Date,
  ): Promise<readonly GeofencingEventRecord[]> {
    const result = await this.database.query<{ event_type: 'ENTER' | 'EXIT'; occurred_at: Date; origin: GeofenceOrigin }>(
      `SELECT event.event_type, event.occurred_at, event.origin
       FROM geofencing_events event
       JOIN geofencing_subscriptions subscription ON subscription.id = event.subscription_id
       WHERE subscription.user_quest_id = $1
         AND event.occurred_at >= $2 AND event.occurred_at <= $3
       ORDER BY event.occurred_at`,
      [userQuestId, windowStart, windowEnd],
    );
    return result.rows.map((row) => ({
      type: row.event_type,
      occurredAt: row.occurred_at,
      origin: row.origin ?? 'NOKIA',
    }));
  }

  private map(row: SubscriptionRow): GeofencingSubscriptionRecord {
    return {
      id: row.id,
      userQuestId: row.user_quest_id,
      placeId: row.place_id,
      providerSubscriptionId: row.provider_subscription_id,
      providerSubscriptionIds: row.provider_subscription_ids ?? (row.provider_subscription_id ? [row.provider_subscription_id] : []),
      status: row.status,
      callbackSecret: row.callback_secret,
      startsAt: row.starts_at,
      expiresAt: row.expires_at,
      origin: row.origin ?? 'NOKIA',
    };
  }

  /// How many geofences Nokia is actively watching for this user. Read-only,
  /// used by the demo surface to show the subscription side is real.
  async countActive(userId: string): Promise<number> {
    const result = await this.database.query<{ count: number }>(
      `SELECT count(*)::integer AS count
       FROM geofencing_subscriptions s
       JOIN user_quests uq ON uq.id = s.user_quest_id
       WHERE uq.user_id = $1 AND s.status = 'active'`,
      [userId],
    );
    return result.rows[0]?.count ?? 0;
  }

}
