import { Type } from 'class-transformer';
import {
  ArrayMaxSize,
  ArrayMinSize,
  IsArray,
  IsIn,
  IsISO8601,
  IsOptional,
  IsUUID,
  ValidateNested,
} from 'class-validator';
import { analyticsEventTypes, analyticsSurfaces } from '../domain/analytics-events.js';

export class AnalyticsEventDto {
  /// Generated by the client so a retried flush is recorded once.
  @IsUUID() clientEventId!: string;

  @IsIn(analyticsEventTypes) eventType!: (typeof analyticsEventTypes)[number];

  @IsUUID() questId!: string;

  @IsIn(analyticsSurfaces) surface!: (typeof analyticsSurfaces)[number];

  /// The post whose card this was raised from, when there was one — a
  /// BSHEEEL pressed on a feed post, a quest opened from a post. This is
  /// what makes "User A's post led to User B's completion" computable
  /// (migration 0049). Absent for events with no source post.
  @IsOptional() @IsUUID() sourceSubmissionId?: string;

  /// When the client says it happened. Clamped server-side into a sane
  /// window around receipt — see `clampOccurredAt` — because a device clock
  /// can be wrong by years and a chart drawn on a bad clock puts real
  /// activity on the wrong day.
  @IsISO8601() occurredAt!: string;
}

export class AnalyticsBatchDto {
  /// Bounded at 200. Telemetry is the one endpoint a client calls without a
  /// user waiting for the answer, which makes it the easiest place to send
  /// something enormous by accident; and the batch is one statement, so the
  /// bound is what keeps that statement's arrays sane.
  @IsArray()
  @ArrayMinSize(1)
  @ArrayMaxSize(200)
  @ValidateNested({ each: true })
  @Type(() => AnalyticsEventDto)
  events!: AnalyticsEventDto[];
}
