// Generate Kysely types from the migrated database; --check detects schema drift.
// Only introspects metadata. Never reads application rows or changes the database.
import pg from 'pg';
import { readFile } from 'node:fs/promises';

const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL, connectionTimeoutMillis: 5000 });
try {
  const { rows: columns } = await pool.query(`
    SELECT table_name, column_name, udt_name, is_nullable, column_default
    FROM information_schema.columns WHERE table_schema = 'public'
    AND table_name NOT IN ('schema_migrations') ORDER BY table_name, ordinal_position
  `);
  const { rows: enums } = await pool.query(`
    SELECT t.typname, e.enumlabel FROM pg_type t JOIN pg_enum e ON e.enumtypid=t.oid
    JOIN pg_namespace n ON n.oid=t.typnamespace WHERE n.nspname='public'
    ORDER BY t.typname,e.enumsortorder
  `);
  if (!columns.length) throw new Error('No public schema: migrate the database first.');
  const enumTypes = new Map();
  for (const row of enums) enumTypes.set(row.typname, [...(enumTypes.get(row.typname) ?? []), JSON.stringify(row.enumlabel)]);
  const scalar = (name) => {
    if (enumTypes.has(name)) return enumTypes.get(name).join(' | ');
    if (name.startsWith('_')) return `Array<${scalar(name.slice(1))}>`;
    if (['int2', 'int4', 'float4', 'float8'].includes(name)) return 'number';
    if (name === 'bool') return 'boolean';
    if (['timestamp', 'timestamptz', 'date'].includes(name)) return 'Timestamp';
    if (['json', 'jsonb'].includes(name)) return 'Json';
    if (name === 'bytea') return 'Buffer';
    if (['uuid', 'text', 'varchar', 'bpchar', 'citext', 'inet', 'int8', 'numeric', 'time', 'timetz'].includes(name)) return 'string';
    throw new Error(`Unmapped PostgreSQL type ${name}; add its actual pg driver representation.`);
  };
  const lines = [
    '// Generated by scripts/database-types.mjs from the migrated public schema.',
    '// Do not hand-edit. CI checks this against a fresh migration replay.',
    "import type { ColumnType, Generated } from 'kysely';",
    '',
    'type Timestamp = ColumnType<Date, Date | string, Date | string>;',
    'type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };',
    'type Json = ColumnType<JsonValue, JsonValue | string, JsonValue | string>;',
    '',
    'export interface Database {',
  ];
  let table;
  for (const column of columns) {
    if (column.table_name !== table) {
      if (table) lines.push('  };');
      table = column.table_name;
      lines.push(`  ${JSON.stringify(table)}: {`);
    }
    let type = scalar(column.udt_name);
    if (column.is_nullable === 'YES') type += ' | null';
    if (column.column_default !== null) type = `Generated<${type}>`;
    lines.push(`    ${JSON.stringify(column.column_name)}: ${type};`);
  }
  lines.push('  };', '}', '');
  const generated = lines.join('\n');
  if (process.argv.includes('--check')) {
    const existing = await readFile(new URL('../src/infrastructure/database/database.types.ts', import.meta.url), 'utf8');
    if (existing !== generated) throw new Error('Database types drifted: regenerate against the latest migrated database.');
    console.log('Database types match the migrated schema.');
  } else {
    process.stdout.write(generated);
  }
} finally {
  await pool.end();
}
