// Generated by scripts/database-types.mjs from the migrated public schema.
// Do not hand-edit. CI checks this against a fresh migration replay.
import type { ColumnType, Generated } from 'kysely';

type Timestamp = ColumnType<Date, Date | string, Date | string>;
type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };
type Json = ColumnType<JsonValue, JsonValue | string, JsonValue | string>;

export interface Database {
  "account_delete_requests": {
    "id": Generated<string>;
    "user_id": string;
    "execute_after": Timestamp;
    "cancelled_at": Timestamp | null;
    "completed_at": Timestamp | null;
    "created_at": Generated<Timestamp>;
  };
  "admin_audit_log": {
    "id": Generated<string>;
    "actor_id": string | null;
    "action": string;
    "target_type": string;
    "target_id": string | null;
    "before_state": Json | null;
    "after_state": Json | null;
    "request_id": string | null;
    "ip_address": string | null;
    "created_at": Generated<Timestamp>;
  };
  "admin_quest_injections": {
    "id": Generated<string>;
    "target_user_id": string;
    "quest_id": string;
    "created_by": string;
    "consumed_at": Timestamp | null;
    "created_at": Generated<Timestamp>;
  };
  "admins": {
    "id": Generated<string>;
    "user_id": string;
    "role": Generated<"moderator" | "super_admin">;
    "created_at": Generated<Timestamp>;
  };
  "agent_runs": {
    "id": Generated<string>;
    "kind": string;
    "subject_type": string;
    "subject_id": string;
    "idempotency_key": string;
    "status": Generated<string>;
    "model": string;
    "prompt_version": string;
    "policy_version": string;
    "input_snapshot": Json;
    "output": Json | null;
    "error_code": string | null;
    "error_message": string | null;
    "started_at": Timestamp | null;
    "completed_at": Timestamp | null;
    "created_at": Generated<Timestamp>;
  };
  "app_config": {
    "key": string;
    "value": Json;
    "description": string | null;
    "is_public": Generated<boolean>;
    "updated_by": string | null;
    "updated_at": Generated<Timestamp>;
  };
  "auth_action_tokens": {
    "id": Generated<string>;
    "user_id": string;
    "purpose": string;
    "token_hash": Buffer;
    "encrypted_token": Buffer;
    "expires_at": Timestamp;
    "consumed_at": Timestamp | null;
    "created_at": Generated<Timestamp>;
  };
  "auth_identities": {
    "id": Generated<string>;
    "user_id": string;
    "provider": string;
    "provider_subject": string;
    "provider_email": string | null;
    "created_at": Generated<Timestamp>;
  };
  "blocked_users": {
    "id": Generated<string>;
    "blocker_id": string;
    "blocked_id": string;
    "created_at": Generated<Timestamp>;
  };
  "business_members": {
    "business_id": string;
    "user_id": string;
    "role": Generated<string>;
    "created_at": Generated<Timestamp>;
  };
  "business_places": {
    "business_id": string;
    "place_id": string;
    "linked_by": string | null;
    "linked_at": Generated<Timestamp>;
  };
  "businesses": {
    "id": Generated<string>;
    "name": string;
    "slug": string;
    "description": Generated<string>;
    "contact_email": string | null;
    "website_url": string | null;
    "logo_url": string | null;
    "status": Generated<string>;
    "created_by": string | null;
    "created_at": Generated<Timestamp>;
    "updated_at": Generated<Timestamp>;
    "analytics_subscribed_at": Timestamp | null;
  };
  "collab_group_members": {
    "id": Generated<string>;
    "group_id": string;
    "user_id": string;
    "user_quest_id": string;
    "joined_at": Generated<Timestamp>;
    "submission_time_seconds": number | null;
  };
  "collab_groups": {
    "id": Generated<string>;
    "quest_id": string;
    "creator_id": string;
    "code": string;
    "mode": Generated<"with" | "versus">;
    "status": Generated<"open" | "active" | "completed" | "expired" | "abandoned" | "closed">;
    "max_members": Generated<number>;
    "expires_at": Timestamp;
    "created_at": Generated<Timestamp>;
  };
  "collab_votes": {
    "id": Generated<string>;
    "group_id": string;
    "voter_id": string;
    "submission_id": string;
    "created_at": Generated<Timestamp>;
  };
  "comments": {
    "id": Generated<string>;
    "submission_id": string;
    "user_id": string;
    "body": string;
    "parent_id": string | null;
    "created_at": Generated<Timestamp>;
    "updated_at": Generated<Timestamp>;
  };
  "cv_evidence": {
    "id": Generated<string>;
    "agent_run_id": string;
    "submission_id": string;
    "provider": string;
    "model_version": string;
    "status": string;
    "result": Generated<Json>;
    "analyzed_at": Timestamp;
    "created_at": Generated<Timestamp>;
  };
  "device_tokens": {
    "id": Generated<string>;
    "user_id": string;
    "token_hash": Buffer;
    "encrypted_token": Buffer;
    "platform": string;
    "last_seen_at": Generated<Timestamp>;
    "created_at": Generated<Timestamp>;
  };
  "feature_flags": {
    "key": string;
    "enabled": Generated<boolean>;
    "rollout_percentage": Generated<number>;
    "rules": Generated<Json>;
    "updated_by": string | null;
    "updated_at": Generated<Timestamp>;
  };
  "follows": {
    "id": Generated<string>;
    "follower_id": string;
    "following_id": string;
    "created_at": Generated<Timestamp>;
  };
  "gdpr_export_log": {
    "id": Generated<string>;
    "user_id": string;
    "requested_at": Generated<Timestamp>;
    "completed_at": Timestamp | null;
    "object_key": string | null;
    "expires_at": Timestamp | null;
  };
  "geofencing_events": {
    "id": Generated<string>;
    "subscription_id": string;
    "event_type": string;
    "occurred_at": Timestamp;
    "received_at": Generated<Timestamp>;
    "provider_event_id": string | null;
  };
  "geofencing_subscriptions": {
    "id": Generated<string>;
    "user_quest_id": string;
    "place_id": string;
    "provider_subscription_id": string | null;
    "status": Generated<string>;
    "callback_secret": string;
    "failure_reason": string | null;
    "starts_at": Timestamp;
    "expires_at": Timestamp;
    "created_at": Generated<Timestamp>;
    "provider_subscription_ids": Generated<Array<string>>;
  };
  "idempotency_keys": {
    "scope": string;
    "key": string;
    "user_id": string | null;
    "request_hash": Buffer;
    "response_status": number | null;
    "response_body": Json | null;
    "locked_until": Timestamp;
    "expires_at": Timestamp;
    "created_at": Generated<Timestamp>;
  };
  "map_countries": {
    "code": string;
    "name": string;
    "geometry_id": string;
  };
  "map_location_evidence": {
    "id": Generated<string>;
    "user_id": string;
    "place_id": string;
    "provider_reference": string;
    "location_verified": boolean;
    "location_retrieved": boolean;
    "geofence_verified": boolean;
    "verified_at": Timestamp;
    "expires_at": Timestamp;
  };
  "map_places": {
    "id": Generated<string>;
    "country_code": string;
    "name": string;
    "description": Generated<string>;
    "city": Generated<string>;
    "category": string;
    "latitude": number;
    "longitude": number;
    "radius_m": Generated<number>;
    "is_published": Generated<boolean>;
    "created_at": Generated<Timestamp>;
  };
  "media_objects": {
    "id": Generated<string>;
    "user_id": string;
    "client_request_id": string;
    "object_key": string;
    "kind": "avatar" | "submission";
    "status": Generated<"pending" | "ready" | "rejected" | "deleted">;
    "content_type": string;
    "declared_size_bytes": string;
    "stored_size_bytes": string | null;
    "etag": string | null;
    "created_at": Generated<Timestamp>;
    "completed_at": Timestamp | null;
    "deleted_at": Timestamp | null;
    "submission_id": string | null;
    "upload_expires_at": Generated<Timestamp>;
    "reclaim_started_at": Timestamp | null;
    "reclaim_lease_until": Timestamp | null;
    "reclaim_token": string | null;
    "reclaim_reason": string | null;
    "storage_deleted_at": Timestamp | null;
    "captured_at": Timestamp | null;
    "width": number | null;
    "height": number | null;
    "perceptual_hash": string | null;
    "forensics": Json | null;
    "forensics_at": Timestamp | null;
    "content_md5": string | null;
  };
  "media_submission_links": {
    "media_object_id": string;
    "submission_id": string;
  };
  "network_evidence": {
    "id": Generated<string>;
    "agent_run_id": string;
    "user_quest_id": string;
    "submission_id": string;
    "capability": string;
    "provider": string;
    "provider_reference": string;
    "outcome": string;
    "result": Generated<Json>;
    "observed_at": Timestamp;
    "valid_until": Timestamp | null;
    "created_at": Generated<Timestamp>;
  };
  "notification_deliveries": {
    "notification_id": string;
    "device_token_id": string;
    "status": Generated<string>;
    "attempts": Generated<number>;
    "fcm_message_name": string | null;
    "last_error": string | null;
    "delivered_at": Timestamp | null;
    "updated_at": Generated<Timestamp>;
    "created_at": Generated<Timestamp>;
  };
  "notifications": {
    "id": Generated<string>;
    "user_id": string;
    "actor_id": string | null;
    "title": string;
    "body": string;
    "type": string;
    "reference_id": string | null;
    "is_read": Generated<boolean>;
    "created_at": Generated<Timestamp>;
  };
  "outbox_events": {
    "id": Generated<string>;
    "aggregate_type": string;
    "aggregate_id": string;
    "event_type": string;
    "payload": Json;
    "occurred_at": Generated<Timestamp>;
    "available_at": Generated<Timestamp>;
    "attempts": Generated<number>;
    "processed_at": Timestamp | null;
    "last_error": string | null;
  };
  "phone_signin_states": {
    "id": Generated<string>;
    "state": string;
    "intent": string;
    "user_id": string | null;
    "age_verified": Generated<boolean>;
    "redirect_uri": string;
    "status": Generated<string>;
    "handoff_code": string | null;
    "result_user_id": string | null;
    "expires_at": Timestamp;
    "handoff_expires_at": Timestamp | null;
    "created_at": Generated<Timestamp>;
    "nonce": string | null;
    "claimed_phone_number": string | null;
    "oauth_flow": string | null;
    "claimed_email": string | null;
  };
  "processed_messages": {
    "consumer": string;
    "message_id": string;
    "processed_at": Generated<Timestamp>;
  };
  "profiles": {
    "id": string;
    "username": string;
    "display_name": Generated<string>;
    "avatar_url": string | null;
    "bio": string | null;
    "xp": Generated<number>;
    "level": Generated<number>;
    "quests_completed": Generated<number>;
    "profile_completed": Generated<boolean>;
    "age_verified": Generated<boolean>;
    "analytics_consent_at": Timestamp | null;
    "accepted_terms_at": Timestamp | null;
    "created_at": Generated<Timestamp>;
    "updated_at": Generated<Timestamp>;
    "streak_reminder_sent_on": Timestamp | null;
    "country_code": string | null;
  };
  "public_deletion_requests": {
    "id": Generated<string>;
    "email": string;
    "note": string | null;
    "handled_at": Timestamp | null;
    "handled_by": string | null;
    "matched_user_id": string | null;
    "created_at": Generated<Timestamp>;
  };
  "quest_chain_steps": {
    "chain_id": string;
    "quest_id": string;
    "step_order": number;
  };
  "quest_chains": {
    "id": Generated<string>;
    "name": string;
    "description": Generated<string>;
    "mode": Generated<string>;
    "is_active": Generated<boolean>;
    "created_by": string | null;
    "created_at": Generated<Timestamp>;
    "updated_at": Generated<Timestamp>;
  };
  "quest_collection_items": {
    "collection_id": string;
    "quest_id": string;
  };
  "quest_collections": {
    "id": Generated<string>;
    "name": string;
    "description": Generated<string>;
    "country_code": string | null;
    "is_published": Generated<boolean>;
    "created_by": string | null;
    "created_at": Generated<Timestamp>;
    "updated_at": Generated<Timestamp>;
  };
  "quest_destinations": {
    "quest_id": string;
    "place_id": string;
    "requires_verification": Generated<boolean>;
  };
  "quest_of_the_day": {
    "id": Generated<string>;
    "quest_id": string;
    "display_date": Timestamp;
    "ticket_no": string | null;
    "bonus_xp": Generated<number>;
    "created_by": string | null;
    "created_at": Generated<Timestamp>;
    "updated_at": Generated<Timestamp>;
    "note": string | null;
  };
  "quest_reroll_log": {
    "id": Generated<string>;
    "user_id": string;
    "user_quest_id": string | null;
    "rerolled_at": Generated<Timestamp>;
    "charged": Generated<boolean>;
  };
  "quest_suggestions": {
    "id": Generated<string>;
    "email": string | null;
    "title": string;
    "description": string;
    "status": Generated<string>;
    "reviewed_by": string | null;
    "reviewed_at": Timestamp | null;
    "created_at": Generated<Timestamp>;
    "category": string;
    "difficulty": string;
    "suggested_by_name": string | null;
    "suggested_by_handle": string | null;
  };
  "quest_verification_contract": {
    "quest_id": string | null;
    "category": string | null;
    "verifiability": "content" | "provenance_only" | "none" | null;
    "evidence_rubric": string | null;
    "may_auto_approve": boolean | null;
    "may_auto_reject": boolean | null;
  };
  "quest_verification_defaults": {
    "category": string;
    "verifiability": "content" | "provenance_only" | "none";
    "evidence_rubric": string;
    "may_auto_approve": Generated<boolean>;
    "may_auto_reject": Generated<boolean>;
    "updated_at": Generated<Timestamp>;
  };
  "quests": {
    "id": Generated<string>;
    "title": string;
    "description": string;
    "category": string;
    "difficulty": string;
    "xp_reward": Generated<number>;
    "duration_hours": Generated<number>;
    "is_active": Generated<boolean>;
    "created_by": string | null;
    "created_at": Generated<Timestamp>;
    "updated_at": Generated<Timestamp>;
    "available_from": Timestamp | null;
    "available_until": Timestamp | null;
    "is_hidden": Generated<boolean>;
    "sponsor_name": string | null;
    "verification_requirements": Json | null;
    "verifiability": "content" | "provenance_only" | "none" | null;
    "evidence_rubric": string | null;
    "may_auto_approve": boolean | null;
    "may_auto_reject": boolean | null;
  };
  "reactions": {
    "id": Generated<string>;
    "submission_id": string;
    "user_id": string;
    "type": "upvote" | "downvote";
    "created_at": Generated<Timestamp>;
  };
  "refresh_sessions": {
    "id": Generated<string>;
    "user_id": string;
    "token_hash": string;
    "family_id": string;
    "user_agent": string | null;
    "ip_address": string | null;
    "expires_at": Timestamp;
    "rotated_at": Timestamp | null;
    "revoked_at": Timestamp | null;
    "created_at": Generated<Timestamp>;
  };
  "reports": {
    "id": Generated<string>;
    "reporter_id": string;
    "reported_type": string;
    "reported_id": string;
    "reason": string;
    "admin_note": string | null;
    "status": Generated<string>;
    "reviewed_by": string | null;
    "reviewed_at": Timestamp | null;
    "created_at": Generated<Timestamp>;
  };
  "saved_map_places": {
    "user_id": string;
    "place_id": string;
    "created_at": Generated<Timestamp>;
  };
  "saved_posts": {
    "id": Generated<string>;
    "user_id": string;
    "submission_id": string;
    "created_at": Generated<Timestamp>;
  };
  "saved_quests": {
    "id": Generated<string>;
    "user_id": string;
    "quest_id": string;
    "created_at": Generated<Timestamp>;
  };
  "submission_verifications": {
    "submission_id": string;
    "state": Generated<string>;
    "verdict": "pass" | "fail" | "unclear" | null;
    "confidence": string | null;
    "rationale": Generated<string>;
    "escalation_reason": Generated<string>;
    "model": Generated<string>;
    "location_verified": boolean | null;
    "location_retrieved": boolean | null;
    "geofence_verified": boolean | null;
    "input_tokens": number | null;
    "output_tokens": number | null;
    "duration_ms": number | null;
    "attempts": Generated<number>;
    "last_error": string | null;
    "resolved_by": string | null;
    "resolved_at": Timestamp | null;
    "queued_at": Generated<Timestamp>;
    "completed_at": Timestamp | null;
    "acted": Generated<boolean>;
    "forensics": Json | null;
    "stage": string | null;
    "relevance": string | null;
    "content_evidence": Json | null;
    "claimed_at": Timestamp | null;
  };
  "submissions": {
    "id": Generated<string>;
    "user_quest_id": string;
    "user_id": string;
    "media_url": string;
    "media_type": Generated<"image" | "video" | "mixed">;
    "caption": string | null;
    "status": Generated<"pending" | "approved" | "rejected">;
    "reviewed_by": string | null;
    "review_note": string | null;
    "submitted_at": Generated<Timestamp>;
    "reviewed_at": Timestamp | null;
    "appeal_note": string | null;
    "appealed": Generated<boolean>;
    "show_in_feed": Generated<boolean>;
    "visibility": Generated<"visible" | "hidden_from_feed" | "deleted">;
    "deleted_at": Timestamp | null;
    "xp_awarded": Generated<boolean>;
    "xp_awarded_amount": Generated<number>;
    "telegram_message_id": string | null;
    "version": Generated<number>;
    "net_score": Generated<string>;
    "moderation_removed_at": Timestamp | null;
    "recommended_xp": number | null;
  };
  "telegram_command_state": {
    "chat_id": string;
    "command": string;
    "step": string;
    "data": Generated<Json>;
    "updated_at": Generated<Timestamp>;
  };
  "telegram_webhook_updates": {
    "update_id": string;
    "status": Generated<string>;
    "locked_until": Generated<Timestamp>;
    "attempts": Generated<number>;
    "last_error": string | null;
    "processed_at": Timestamp | null;
    "created_at": Generated<Timestamp>;
    "updated_at": Generated<Timestamp>;
  };
  "user_quests": {
    "id": Generated<string>;
    "user_id": string;
    "quest_id": string;
    "status": Generated<"assigned" | "submitted" | "approved" | "rejected" | "expired" | "abandoned">;
    "assigned_at": Generated<Timestamp>;
    "completed_at": Timestamp | null;
    "expires_at": Timestamp;
    "version": Generated<number>;
    "assignment_distance_meters": number | null;
  };
  "users": {
    "id": Generated<string>;
    "email": string | null;
    "password_hash": string | null;
    "email_verified_at": Timestamp | null;
    "status": Generated<"active" | "suspended" | "banned" | "deletion_pending">;
    "token_version": Generated<number>;
    "last_login_at": Timestamp | null;
    "created_at": Generated<Timestamp>;
    "updated_at": Generated<Timestamp>;
    "deleted_at": Timestamp | null;
    "phone_number": string | null;
    "phone_verified_at": Timestamp | null;
  };
  "waitlist": {
    "id": Generated<string>;
    "email": string;
    "source": string | null;
    "created_at": Generated<Timestamp>;
  };
}
