BEGIN;

-- The event store (#81 §28), and the reason the funnel above "activation"
-- has been unbuildable.
--
-- Everything from activation down already has an authoritative source:
-- `user_quests` records who started a quest, `submissions` who finished it,
-- `network_evidence` whether the network agreed they were there. Those are
-- facts the server wrote while doing the work.
--
-- Nothing records that a quest was ever *seen*. Impressions, detail views,
-- BSHEEEL presses and shares leave no trace anywhere in the schema, so
-- §7/§8/§9-EXPOSURE were not "not done yet" — they were not computable.
--
-- Two rules this table is built around, both from §28's own warning not to
-- introduce events blindly:
--
-- 1. It stores ONLY what has no other source. There is no `quest_assigned`
--    or `quest_approved` event here, because `user_quests` and `submissions`
--    already say so and a second source would drift from the first. The
--    funnel is assembled from both: the top from here, the bottom from the
--    tables that own it.
--
-- 2. What is in here is **client-attested**. A phone reports that it drew a
--    quest card; nobody can verify that from the server side. Completions
--    are server-authoritative. Those two kinds of number must not be
--    presented to a business as equally reliable, which is why the API
--    labels them and the dashboard says so out loud. The same discipline
--    §10 applies to revenue applies here.

CREATE TABLE analytics_events (
  id bigserial PRIMARY KEY,

  -- Generated by the client so a retried batch is recorded once. The unique
  -- index below is what makes ingest idempotent: a phone that loses its
  -- connection mid-flush resends the same ids, and resending must not
  -- inflate a business's impressions.
  client_event_id uuid NOT NULL,

  -- CASCADE, deliberately. Telemetry about a person is not a record the
  -- product needs to keep: deleting the account deletes the trail, which is
  -- what account deletion already promises elsewhere.
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  -- A closed set. Adding one means adding it here, in the domain's
  -- `analyticsEventTypes`, and in the ingest DTO — three places on purpose,
  -- so an event type cannot arrive that nothing knows how to aggregate.
  event_type text NOT NULL CHECK (event_type IN (
    'quest_impression',
    'quest_detail_view',
    'quest_bsheeel',
    'quest_share'
  )),

  quest_id uuid NOT NULL REFERENCES quests(id) ON DELETE CASCADE,

  -- Where it happened, so a business can tell "seen while scrolling the
  -- feed" from "found on the map". Closed set for the same reason.
  surface text NOT NULL CHECK (surface IN (
    'feed', 'map', 'home', 'search', 'country', 'quest_detail'
  )),

  -- When the client says it happened, and when we received it. Both, because
  -- a device clock can be wrong by years and a daily chart drawn on a bad
  -- clock puts real activity on the wrong day. The ingest clamps
  -- `occurred_at` into a sane window around `received_at` — see
  -- `clampOccurredAt` — and keeps both so the clamping is visible rather
  -- than silent.
  occurred_at timestamptz NOT NULL,
  received_at timestamptz NOT NULL DEFAULT now()
);

-- Idempotency. Scoped per user: two phones cannot collide on a uuid in
-- practice, and scoping it means one user's replay cannot be blocked by
-- another's id.
CREATE UNIQUE INDEX analytics_events_client_id_idx
  ON analytics_events (user_id, client_event_id);

-- The funnel query: events for a set of quests, by type, over a window,
-- counting distinct users. Leading with quest_id because the business scope
-- resolves to a quest set first (business_places → quest_destinations).
CREATE INDEX analytics_events_quest_idx
  ON analytics_events (quest_id, event_type, occurred_at);

-- Retention is not implemented here and should be before this table is
-- large. Raw per-user telemetry has no reason to outlive the aggregates
-- drawn from it; a rollup table plus a delete of anything older than the
-- rollup window is the obvious next step, and the reason this table has no
-- other purpose than being aggregated.
COMMENT ON TABLE analytics_events IS
  'Append-only, client-attested exposure telemetry (#81 §28). Never exposed '
  'per-row to a business: aggregates only. No retention sweep yet.';

COMMIT;
