BEGIN;

-- Where a geofence event actually came from.
--
-- Nokia's geofencing product is subscription-based: we register a webhook and
-- the network pushes entry/exit events to it later. On a laptop nothing can
-- push to us, so the demo harness generates a Nokia-shaped CloudEvent and
-- delivers it to our own callback over real HTTP — real bearer authentication,
-- real parser, real persistence, real recovery. That exercises everything we
-- own, which is the point of it.
--
-- What it must never do is let the resulting evidence read as "Nokia says the
-- device entered the area". It does not. So provenance is recorded, and it is
-- recorded on the SUBSCRIPTION rather than guessed per request:
--
--   * a subscription the CAMARA adapter created exists on Nokia's side, so an
--     event arriving on it came from Nokia;
--   * a subscription the harness created exists nowhere but here, so Nokia
--     cannot deliver to it, and an event on it is ours by construction.
--
-- That means the callback endpoint needs no test-only branch, no extra header
-- and no way to assert its own provenance — which is what keeps the harness
-- honest rather than a back door wearing a label.
ALTER TABLE geofencing_subscriptions
  ADD COLUMN IF NOT EXISTS origin text NOT NULL DEFAULT 'NOKIA';

ALTER TABLE geofencing_subscriptions DROP CONSTRAINT IF EXISTS geofencing_subscriptions_origin_check;
ALTER TABLE geofencing_subscriptions ADD CONSTRAINT geofencing_subscriptions_origin_check
  CHECK (origin IN ('NOKIA', 'DEMO_HARNESS'));

COMMENT ON COLUMN geofencing_subscriptions.origin IS
  'NOKIA — registered with Network-as-Code, events are delivered by the network. '
  'DEMO_HARNESS — created by the hackathon harness; exists nowhere but here, so '
  'any event on it was generated by us and must never be shown as Nokia-delivered.';

-- Copied onto the event at record time rather than joined at read time: an
-- event is a historical fact, and it should carry where it came from even if
-- the subscription is later deleted or re-pointed.
ALTER TABLE geofencing_events
  ADD COLUMN IF NOT EXISTS origin text NOT NULL DEFAULT 'NOKIA';

ALTER TABLE geofencing_events DROP CONSTRAINT IF EXISTS geofencing_events_origin_check;
ALTER TABLE geofencing_events ADD CONSTRAINT geofencing_events_origin_check
  CHECK (origin IN ('NOKIA', 'DEMO_HARNESS'));

COMMENT ON COLUMN geofencing_events.origin IS
  'Inherited from the subscription when the callback recorded it. DEMO_HARNESS '
  'events are real deliveries through the real webhook — they are simply not '
  'evidence that a carrier observed anything.';

COMMIT;
