BEGIN;

-- A third provenance, and the reason it exists is a measurement.
--
-- Nokia's geofencing product answers `404 {"detail":"Target not found"}` for
-- any device the network does not know. In this sandbox the only devices that
-- exist are Nokia's simulator MSISDNs (+9999999xxxx), so a geofence opened for
-- a real player's number — every seeded account is a +961 one — fails before
-- it is ever registered. That failure was being reported as
-- "Provider returned HTTP 404", which reads as an outage or a missing
-- entitlement and is neither: geofencing is entitled and the routing is
-- correct, verified 2026-09-13 by registering a subscription for +99999991001
-- and receiving 201 Created on the same key and the same client.
--
-- So a demo deployment opens the watch against a simulator device instead.
-- That is a REAL Nokia subscription — Nokia holds it, Nokia would deliver to
-- our sink, cancelling it is a real call — which is exactly what makes it
-- worth distinguishing from both of the existing origins:
--
--   * NOKIA         — registered for the player's own device. Events are the
--                     carrier observing that player.
--   * NOKIA_SIMULATOR — registered with Nokia, but for a simulator identity
--                     standing in for the player's device. The subscription is
--                     real; the *subject* is not the player. Silence on it is
--                     therefore not evidence the player stayed away.
--   * DEMO_HARNESS  — exists nowhere but here.
--
-- The distinction matters in exactly one place and it is a safety one:
-- `CamaraEvidenceAdapter.geofencing` may only answer CONTRADICTED when the
-- network was watching the device it is making a claim about.
ALTER TABLE geofencing_subscriptions DROP CONSTRAINT IF EXISTS geofencing_subscriptions_origin_check;
ALTER TABLE geofencing_subscriptions ADD CONSTRAINT geofencing_subscriptions_origin_check
  CHECK (origin IN ('NOKIA', 'NOKIA_SIMULATOR', 'DEMO_HARNESS'));

ALTER TABLE geofencing_events DROP CONSTRAINT IF EXISTS geofencing_events_origin_check;
ALTER TABLE geofencing_events ADD CONSTRAINT geofencing_events_origin_check
  CHECK (origin IN ('NOKIA', 'NOKIA_SIMULATOR', 'DEMO_HARNESS'));

COMMENT ON COLUMN geofencing_subscriptions.origin IS
  'NOKIA — registered with Network-as-Code for the player''s own device. '
  'NOKIA_SIMULATOR — a real Network-as-Code subscription, but registered for a '
  'Nokia simulator identity standing in for that device, because the sandbox '
  'network knows no other devices. DEMO_HARNESS — created by the hackathon '
  'harness; exists nowhere but here, so any event on it was generated by us.';

COMMIT;
